#!/bin/sh
# Regenerates src/features/xattrs/mditem_names.rs from `mdimport -A`, the
# Spotlight schema dump (columns: key, display name, description, keywords —
# separated by two tabs, each value in single quotes, '(null)' when absent).
# Run on macOS and commit the result.
set -eu

repo="$(cd "$(dirname "$0")/.." && pwd)"
out="$repo/src/features/xattrs/mditem_names.rs"
mkdir -p "$(dirname "$out")"

{
    echo "// Generated by scripts/generate-mditem-names.sh — do not edit."
    echo "// Spotlight attribute schema from \`mdimport -A\` (macOS $(sw_vers -productVersion))."
    echo "// Columns: key, display name, description, keywords (empty string when absent)."
    echo "// Sorted by key so lookups can binary-search."
    echo "#[rustfmt::skip]"
    echo "pub(super) static SCHEMA: &[(&str, &str, &str, &str)] = &["
    mdimport -A | awk -F '\t\t' '
        function unq(s) { return substr(s, 2, length(s) - 2) }  # strip surrounding quotes
        function esc(s) { gsub(/\\/, "\\\\", s); gsub(/"/, "\\\"", s); return s }
        NF >= 2 {
            key = unq($1)
            name = unq($2)
            if (key == "" || name == "" || name == "(null)") next
            # Apple vocabulary only — third-party Spotlight importers on the
            # generating machine also show up in mdimport -A.
            if (key !~ /^(_?kMDItem|com_apple_)/) next
            desc = (NF >= 3) ? unq($3) : ""
            kw   = (NF >= 4) ? unq($4) : ""
            if (desc == "(null)") desc = ""
            if (kw == "(null)") kw = ""
            printf "    (\"%s\", \"%s\", \"%s\", \"%s\"),\n", esc(key), esc(name), esc(desc), esc(kw)
        }
    ' | LC_ALL=C sort -u
    echo "];"
} > "$out"

echo "wrote $out ($(grep -c '^    (' "$out") entries)"
