#!/bin/sh
# Regenerates src/features/xattrs/mditem_names.rs from `mdimport -A`, the
# Spotlight schema dump (columns: key, display name, description, keywords —
# separated by two tabs, each value in single quotes, '(null)' when absent).
# Run on macOS and commit the result.
set -eu

repo="$(cd "$(dirname "$0")/.." && pwd)"
out="$repo/src/features/xattrs/mditem_names.rs"
mkdir -p "$(dirname "$out")"

{
    echo "// Generated by scripts/generate-mditem-names.sh — do not edit."
    echo "// Spotlight attribute display names from \`mdimport -A\` (macOS $(sw_vers -productVersion))."
    echo "// Sorted by key so lookups can binary-search."
    echo "#[rustfmt::skip]"
    echo "pub(super) static DISPLAY_NAMES: &[(&str, &str)] = &["
    mdimport -A | awk -F '\t\t' '
        NF >= 2 {
            key = substr($1, 2, length($1) - 2)
            name = substr($2, 2, length($2) - 2)
            if (key == "" || name == "" || name == "(null)") next
            # Apple vocabulary only — third-party Spotlight importers on the
            # generating machine also show up in mdimport -A.
            if (key !~ /^(_?kMDItem|com_apple_)/) next
            gsub(/\\/, "\\\\", key); gsub(/"/, "\\\"", key)
            gsub(/\\/, "\\\\", name); gsub(/"/, "\\\"", name)
            printf "    (\"%s\", \"%s\"),\n", key, name
        }
    ' | LC_ALL=C sort -u
    echo "];"
} > "$out"

echo "wrote $out ($(grep -c '^    (' "$out") entries)"
